### PR TITLE
Processing of the DefineBitsLossLess2's data ( alpha ) 

### PR DESCRIPTION
**Pull request by GrenadeJane**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/swf/20)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[format/swf/exporters/SWFLiteExporter.hx, line 232 [r1]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOEYlYND0qlfJ45uR8l:-KOEYlYND0qlfJ45uR8m:825617913) ([raw file](https://github.com/fishingcactus/swf/blob/9bc7e52a2692b38ae8ef43f659cec116a8d911ec/format/swf/exporters/SWFLiteExporter.hx#L232)):_

> ``` Haxe
>               var data:TagDefineBitsLossless2 = cast tag;
> 
>               var colorTable = new Array <Int> ();
> ```

any reason not to define it as Array<ARGB>?

---

_[format/swf/exporters/SWFLiteExporter.hx, line 254 [r1]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOEhLS6PhZFPrwYInx9:-KOEhLS6PhZFPrwYInxA:-2113971984) ([raw file](https://github.com/fishingcactus/swf/blob/9bc7e52a2692b38ae8ef43f659cec116a8d911ec/format/swf/exporters/SWFLiteExporter.hx#L254)):_

> ``` Haxe
>                var values = Bytes.alloc ((data.bitmapWidth  + 1)* data.bitmapHeight * 4);
>                var indexImage = 0 ;
>                var index:Int = 0;
> ```

can be moved to a tighter scope

---

_[format/swf/exporters/SWFLiteExporter.hx, line 258 [r1]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOEgkhX0jcoZd4VP7KK:-KOEgkhY8t_1Jaf4RiXw:-1713073127) ([raw file](https://github.com/fishingcactus/swf/blob/9bc7e52a2692b38ae8ef43f659cec116a8d911ec/format/swf/exporters/SWFLiteExporter.hx#L258)):_

> ``` Haxe
>                for ( y in 0...data.bitmapHeight ){
> 
>                    indexImage =  y * data.bitmapWidth * 4 + y ;                   
> ```

extra whites spaces at the end of the line (and also in a few other places in this file)

---

_[format/swf/exporters/SWFLiteExporter.hx, line 296 [r1]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOEncH2TSZU5S9Ak-US:-KOEncH2TSZU5S9Ak-UT:-1355986355) ([raw file](https://github.com/fishingcactus/swf/blob/9bc7e52a2692b38ae8ef43f659cec116a8d911ec/format/swf/exporters/SWFLiteExporter.hx#L296)):_

>  var bitmapData = new BitmapData (data.bitmapWidth, data.bitmapHeight, true);
> 
> ```
>                bitmapData.image.buffer.premultiplied = false;
>                bitmapData.setPixels (bitmapData.rect, buffer);
>                bitmapData.image.buffer.premultiplied = true;
>                bitmapData.image.premultiplied = false;
> 
>                byteArray = bitmapData.encode (bitmapData.rect, new PNGEncoderOptions ());
>                type = BitmapType.PNG;
> ```

Duplicate code... can be removed by reordering tests

---

_[format/swf/exporters/SWFLiteExporter.hx, line 887 [r1]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOEVKln-rBvtjosG9Wn:-KOEVKln-rBvtjosG9Wo:-2120245195) ([raw file](https://github.com/fishingcactus/swf/blob/9bc7e52a2692b38ae8ef43f659cec116a8d911ec/format/swf/exporters/SWFLiteExporter.hx#L887)):_

> ``` Haxe
>               return addSprite (cast tag);
> 
>           } else if (Std.is (tag, TagDefineBits) || Std.is (tag, TagDefineBitsJPEG2) || Std.is (tag, TagDefineBitsLossless) || Std.is ( tag, TagDefineBitsLossless2 )) {      
> ```

Testing for TagDefineBitsLossless2 is unnecessary as it should already match TagDefineBitsLossless

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/swf/20)_

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

_[format/swf/exporters/SWFLiteExporter.hx, line 242 [r2]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOF3WskWvwBUrhb8Ykx:-KOF3WskWvwBUrhb8Yky:-590422726) ([raw file](https://github.com/fishingcactus/swf/blob/a2436a7ca7b21e0a801fa872177573b1ddbe4c72/format/swf/exporters/SWFLiteExporter.hx#L242)):_

> ``` Haxe
>                for (i in 0...data.bitmapColorTableSize ) {
> 
>                    var color:RGBA = new RGBA(); 
> ```

Unnecessary memory traffic. Color is newed, barely used and then thrown away.

Either use 4 unsigned int, or put the new outside the loop

---

_[format/swf/exporters/SWFLiteExporter.hx, line 249 [r2]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOF57RrnIGeVJXCWDaj:-KOF57RsQKXGMFRfjgzq:1797041345) ([raw file](https://github.com/fishingcactus/swf/blob/a2436a7ca7b21e0a801fa872177573b1ddbe4c72/format/swf/exporters/SWFLiteExporter.hx#L249)):_

> ``` Haxe
>                    color.r = buffer.readUnsignedByte ();
> 
>                    colorTable.push ((color.a << 24) + (color.b << 16) + (color.g << 8) + color.r);
> ```

Why reading the file in 2 passes, you could fill the buffer without going though an array

---

_[format/swf/exporters/SWFLiteExporter.hx, line 265 [r2]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOF4i9HgTf2MP-xMyyG:-KOF4i9HgTf2MP-xMyyH:-917199123) ([raw file](https://github.com/fishingcactus/swf/blob/a2436a7ca7b21e0a801fa872177573b1ddbe4c72/format/swf/exporters/SWFLiteExporter.hx#L265)):_

> ``` Haxe
> 
>                        index =  buffer.readUnsignedByte ();   
>                        if (index >= 0 && index < colorTable.length) {
> ```

as you read unsigned byte, they are all `>= 0`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/swf/20)_

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/swf/20)_

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[format/swf/exporters/SWFLiteExporter.hx, line 265 [r2]](https://reviewable.io:443/reviews/fishingcactus/swf/20#-KOF4i9HgTf2MP-xMyyG:-KOG3ubw0BfhJslTYA8x:-1636517165) ([raw file](https://github.com/fishingcactus/swf/blob/a2436a7ca7b21e0a801fa872177573b1ddbe4c72/format/swf/exporters/SWFLiteExporter.hx#L265)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> as you read unsigned byte, they are all `>= 0`
> </details>
> Furthermore, and as discussed, this should not happen (or we would end up with fewer texels than defined in the header). Better throw an error of just discard the test...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/swf/20)_

**Pull request closed without merging**
